### ISSUE TITLE
Is it possible to run async function on user action?

### ISSUE THREAD

**Issue by fbjorn** [square/svelte-store#14]
Hi,

As far as I understand, this library is extremely useful when you want to retrieve some data on a page load. But I tried to make it work for another pretty common use case - user action. For example, button click:

```svelte
<script lang="ts">
  import { asyncReadable } from "@square/svelte-store"

  const data = asyncReadable(undefined, async () => {
    const resp = await fetch("https://catfact.ninja/fact")
    console.log(resp)
    return await resp.json()
  })
</script>

<button on:click={() => data.load && data.load()}>Fetch data</button>

<div>{JSON.stringify($data)}</div>
```

Unfortunately, the server (I'm using SvelteKit) is issuing the network request during the render, not on click handler. It seems like the problem is in the template, cause when I comment out this line:
```svelte
<div>{JSON.stringify($data)}</div>
```
Then it doesn't try to load content on a first load. I somehow expected that it would use default value, until you call `.load()` somewhere, either in one of callbacks, or in template using `{#await}`. But seems that it calls a `load` under the hood when I access the store (what's the point of initial value then?).

I also tried something like this (which didn't help either)
```svelte
<script lang="ts">
  import { asyncReadable } from "@square/svelte-store"

  let requestIsLoading = false
  const data = asyncReadable(undefined, async () => {
    const resp = await fetch("https://catfact.ninja/fact")
    return await resp.json()
  })
</script>

<button on:click={() => (requestIsLoading = true)}>Fetch data</button>

{#if requestIsLoading}
  {#await data.load?.()}
    <div>loading</div>
  {:then}
    <div>{JSON.stringify($data)}</div>
  {/await}
{/if}

```

Would appreciate any feedback regarding this direction. Thanks in advance.

**Comment by Akolyte01** [comment]
Hey there!

So what is happening in your example is this: by including `$data` in your template you are creating a subscription to the store. When an async store gets its first subscriber it will begin it's load process. So including that subscription in your template means that the store will attempt to load as soon as you mount the component. 

There are a couple ways you could approach this. In your example you are manually controlling the loading and lifecycle of the asynchronous data, so it may be you don't want to use the async stores at all and handle things manually. For example

```
<script lang="ts">
  let resolver;
  const loadPromise = new Promise((resolve) => (resolver = resolve));
  const loadData = async () => {
    const resp = await fetch("https://catfact.ninja/fact");
    const data = await resp.json();
    resolver(data);
  };
</script>

<button on:click={loadData}>Fetch data</button>
{#await loadPromise then loadedData}
  <p>{loadedData}</p>
{/await}
```
If you need `data` to be in a store (so that you can react to it throughout your application) you can add a step where you write to a regular `writable` store before resolving.
  
If your use case is more complicated and you'd like to hook into other  features of asynchronous stores you could write things like this....
Let's imagine a scenario where you need to fetch user data for a specified date. So in order to fetch the data you need 1. a user token (from an asyncReadable store) and 2. a date (selected by the user)
  
```
<script lang="ts">
  let userToken; //asyncReadable store 
  const date = writable();
    
  const userData = asyncReadable(
    [userToken, date], 
    async ([$userToken, $date]) => { 
      if(!$date) {
        return undefined;
      }
      return await fetchJson(`https://catfact.ninja/userData/${$userToken}/${$date}`);
    }
  );
</script>
  
<button on:click={date.set(// some date string from picker)}>Fetch data</button>
{#if $userData}
  <p>{$userData}</p>
{/await}
```

When you write to 'date' it will kick of the asynchronous functionality of the store. This is a little awkward because when userToken loads, userData's 'load' promise will resolve even if nothing has been written to `date`. This means the load function can't be use for lifecycle gating, and it could screw up any asyncDerived stores that try to derive from that store. 

With that in mind I'll be trying out some alternative solutions. But hopefully this unblocks you until then.

**Comment by Akolyte01** [comment]
Hello @fbjorn ! The release of @square/svelte-store 0.2.0 may be of interest to you. Now in 0.2.0 readable and writable stores have load functionality. This means you can address your problem like this:

```
<script lang="ts">
  import { asyncReadable } from "@square/svelte-store"

  const userInput = writable(); 

  const data = asyncDerived(userInput, async ($userInput) => {
    const resp = await fetch(`https://catfact.ninja/fact/${$userInput}`);
    console.log(resp);
    return await resp.json();
  })
</script>

<button on:click={() => userInput.set('someData')}>Fetch data</button>
{#await data.load()}
  <div>{JSON.stringify($data)}</div>
{/await}
```

**Comment by Akolyte01** [comment]
The example I wrote was for a one time user action use case, such as consenting to being tracked after loading the page, or confirming their age, country, etc. 

 If you want a store that fetches new data whenver someone presses a button, you would accomplish that by flagging the store as reloadable and using `reload` as you suggested.
