### ISSUE TITLE
Add sessionStorage and localStorage functionality

### ISSUE THREAD

**Issue by miedzikd** [square/svelte-store#24]
Hello from Poland :)
I really appreciate what you are doing :) your module helps me keep my code as clean as possible :)

What do you think about adding sessionStorage and localStorage functionality?

I did something like that for myself and I'm quite happy about that. This is how this can look for `asyncReadable` function:
```js
export const asyncSessionReadable = <T>(sessionItemName: string, initial: T, loadFunction: () => Promise<T>, reloadable?: boolean): Loadable<T> => {
    const finalLoadFunction = async () => {
        const result = await loadFunction();
        sessionStorage.setItem(sessionItemName, JSON.stringify(result));
        return result;
    };

    const { subscribe, load } = asyncReadable(
        {},
        async () => {
            if (sessionStorage.getItem(sessionItemName)) {
                return JSON.parse(sessionStorage.getItem(sessionItemName));
            }
            const result = await finalLoadFunction();
            return result;
        },
        reloadable,
    );

    return {
        subscribe,
        load,
        reload: finalLoadFunction,
    };
};
```

**Comment by Akolyte01** [comment]
Interesting! So to confirm how this works....
This store lets you grab some data asynchronously, and then save that to sessionStorage. However, if there is already matching entry in sessionStorage it short circuits and gives you that data instead of performing the async fetching of the data. If you call `reload` on the store it will force new async data to be pulled and overwrite anything in sessionStorage. 

Is that correct? Can you provide a usage example?

**Comment by miedzikd** [comment]
yes, you got this correct ;) Thanks to this you make fewer requests, but if you want you can still call the `reload` method.

This can be an example of usage:
```js
export const configStore = asyncSessionReadable(
    'configStore',
    {},
    async () => {
        const response = await fetch('/settings/get-configs');
        const config = await response.json();
        return config;
    },
);
```

As you can see, it's almost the same as default usage, just one parameter more :)

In svelte file I still can use `.load()` and `.reload()` function.

**Comment by candidosales** [comment]
@miedzikd, I'm using https://github.com/joshnuss/svelte-local-storage-store , maybe this could help you.

**Comment by miedzikd** [comment]
Hej @candidosales 
Yes i use it too... 
Both packages are very simple and powerful 
But I think will be great to have combined functionally too ;)

**Comment by Akolyte01** [comment]
Okay I've spent some time thinking about this.

This is a cool use case and I think it makes sense to include eventually, but that will likely be deferred for a while in order to address some design questions surrounding it. 

One question regards reloading. The way reload works for this store makes total sense in the context of this store, but would cause some compatibility problems with the reload functionality of other stores. In the snippet indicating the store as 'reloadable' or not does not actually change functionality--the internal asyncReadable store is declared `reloadable` but the reload function of that store is never called. Instead a reload function is always returned by the custom store. We'd run into issues here when deriving from this store.

The second regards how to scale this pattern to the other kinds of stores. There would need to be an asyncSessionWritable store, asyncLocalReadable, etc. That would greatly increase the types of stores that are included in the package. I think I could get an alternative pattern to work, where you'd instead wrap a some part of the store declaration in a function that adds on session or local storage, but that will take some experimentation. 
This brings up further questions in regards to how derived and writable versions of the stores should work. For example lets say you wanted to have a store that fetches from a server when corresponding local storage is missing, but also derives from a different store. If the parent store changes value should it fetch new data from the server? Or go with the local storage data it already has?


These are surmountable problems, but will take some dedicated time to address. The idea is excellent!

**Comment by miedzikd** [comment]
Your thoughts are as true as can be!
Thank you @Akolyte01 for your time. 
I will be happy to adapt to different pattern :)

**Comment by Akolyte01** [comment]
@miedzikd Okay I think the pattern we will want to adopt here is going to be similar to [oshnuss/svelte-local-storage-store](https://github.com/joshnuss/svelte-local-storage-store)

We will have a store called storage that you can call in a manner similar to this:

```
const myConfig = storage(someDefaultConfig, 'configStore');
```

This would create a writable store whose initial value is equal to 'configStore' in localStorage if it is present, otherwise it will initialize to `someDefaultConfig` and also write that value to localStorage. 

Calling `set` or `update` on this store would correspondingly update the localStorage entry.

However this store may additionally be called like this:

```
const myRemoteConfig = asyncReadable(
    someDefaultConfig, 
    async () => {
        const response = await fetch('/settings/get-configs');
        const config = await response.json();
        return config;
    },
    true
);

const myConfig = storage(myRemoteConfig, 'configStore', true);
```

In addition to being able to provide initial values for myConfig, we can pass in a Loadable store. If we do so, when myConfig store initializes, if there is no 'configStore' entry in localStorage, it will wait the loading of myRemoteConfig and then store the resulting value to localStorage and finish loading itself.
 
By declaring the store as reloadable with the third parameter you can call `reload` on the store, which will reload any parent passed in and then write the reloaded value to localStorage (and its own value). 

In this way we separate storage behavior from async behavior. `myRemoteConfig` will only be loaded if 'configStore' is not found in local storage, so it preserves the lazy loading built into your implementation. However it also allows for `storage` stores to be used independently in cases where asynchronous behavior is not needed. 

The exact implementation and syntax is subject to change (need to add ability to choose between local and session storage, etc). Would this pattern cover your use cases? Or do you have any concerns?

**Comment by miedzikd** [comment]
Hello @Akolyte01 :)
Thanks for your effort! Yes, that sounds really great! :) 

I have just one question: Did `.reload()` will be still available from `myConfig`?
As you mentioned at the end of your comment, the ability to choose between local and session storage is needed too :)

No more concerns ;)

**Comment by Akolyte01** [comment]
If you provide `true` as a third argument for `myConfig` it would have a `reload` function. If `myRemoteConfig` is declared to be reloadable that store will reload and then `myConfig` and the corresponding storage item will be set to this value. If `myRemoteConfig` is not reloadable, `myConfig` and the storage item will be set to the value of `myRemoteConfig` without performing any new async behavior.

**Comment by Akolyte01** [comment]
As a heads up this feature is in beta testing at the moment and should be released soon!

**Comment by Akolyte01** [comment]
Okay took longer than expected but 1.0.10 is now out! 'persisted' stores can be used for this use case

**Comment by miedzikd** [comment]
Thank you so much @Akolyte01 ! :)
