### ISSUE TITLE
Document naive await values are not reactive

### ISSUE THREAD

**Issue by smblee** [square/svelte-store#30]
currently we have the following in the documentation (which is reactive)

```svelte
{#await myLoadableStore.load()}
 <p>Currently loading...</p>
{:then}
 <p>Your loaded data is: {$myLoadableStore}</p>
{/await}
```

we could warn that the following won't be reactive

```svelte
{#await myLoadableStore.load()}
 <p>Currently loading...</p>
{:then myValue}
 <p>Your loaded data is: {myValue}</p>
{/await}
```

**Comment by Akolyte01** [comment]
So I've been thinking about this off and on for a while but I don't think there's a good solution here. This should be achieved by linting but linting svelte templates is buggier and less standardized than eslint for typescript. We've changed our linting approaches multiple times and so I'm not sure I'm willing to endorse one approach by writing a rule for it. 

If someone wants to write a rule for this I'm very open to including it in the repo, but I'm going to close this otherwise.
